#!/bin/sh

usage () {
  cat << EOF
usage: toonepage <pddpsource>.xml
EOF
}

[ $# -eq 0 ] && { usage; exit 1; }

infile="$1"

SOURCE_NAME="$(basename "${infile}")"
SOURCE_STUB="$(basename "${SOURCE_NAME}" .xml)"

[ "${SOURCE_STUB}" = "${SOURCE_NAME}" ] && { usage; exit 1; }

xmllint >/dev/null --xinclude --postvalid "${infile}"
xsltproc --nonet --xinclude \
 --stringparam html.stylesheet pddp.css \
 -o "$SOURCE_STUB.html" \
 /usr/share/xml/docbook/stylesheet/nwalsh/html/docbook.xsl \
 "${infile}"
